{
  "sksl": {
    "entrypoint": "shader_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform float dissolve_value;\nuniform float burn_size;\nuniform shader uTexture;\nuniform half2 uTexture_size;\nuniform shader dissolve_texture;\nuniform half2 dissolve_texture_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 coo = FLT_flutter_local_FlutterFragCoord() / uSize;\n    vec4 main_texture = uTexture.eval(uTexture_size * ( coo));\n    vec4 color = uTexture.eval(uTexture_size * ( coo));\n    vec4 noise_texture = dissolve_texture.eval(dissolve_texture_size * ( coo));\n    float burn_size_step = (burn_size * step(0.001000000047497451305389404296875, dissolve_value)) * step(dissolve_value, 0.999000012874603271484375);\n    float threshold = smoothstep(noise_texture.x - burn_size_step, noise_texture.x, dissolve_value);\n    float border = smoothstep(noise_texture.x, noise_texture.x + burn_size_step, dissolve_value);\n    vec4 burn_color = vec4(1.0, 0.0, 0.0, 0.100000001490116119384765625);\n    burn_color.w = 0.5;\n    color.w *= threshold;\n    vec3 _99 = mix(burn_color.xyz, main_texture.xyz, vec3(border));\n    color.x = _99.x;\n    color.y = _99.y;\n    color.z = _99.z;\n    fragColor = color;\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 1,
        "name": "uTexture",
        "rows": 1,
        "type": 12
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 2,
        "name": "dissolve_texture",
        "rows": 1,
        "type": 12
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "dissolve_value",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "burn_size",
        "rows": 1,
        "type": 10
      }
    ]
  }
}